[project]
authors = [
    "Ilya Segal",
    "Mikhail Mikhasenko",
    "Remco de Boer",
]
channels = ["conda-forge"]
description = "Prototype for the amplitude model serialization format"
documentation = "https://rub-ep1.github.io/amplitude-serialization"
homepage = "https://rub-ep1.github.io/amplitude-serialization"
license = "MIT"
license-file = "LICENSE"
name = "amplitude-serialization"
platforms = [
    "linux-64",
    "osx-64",
]

[dependencies]
julia = ">=1.10.0"
python = ">=3.8.0"

[pypi-dependencies]
pre-commit = "*"
