[project]
authors = [
    "Ilya Segal",
    "Mikhail Mikhasenko",
    "Remco de Boer",
]
channels = ["conda-forge"]
description = "Prototype for the amplitude model serialization format"
documentation = "https://rub-ep1.github.io/amplitude-serialization"
homepage = "https://rub-ep1.github.io/amplitude-serialization"
license = "MIT"
license-file = "LICENSE"
name = "amplitude-serialization"
platforms = [
    "linux-64",
    "osx-64",
    "osx-arm64",
]
repository = "https://github.com/RUB-EP1/amplitude-serialization"

[dependencies]
juliaup = "*"
python = ">=3.8.0"
quarto = "*"

[pypi-dependencies]
ampform-dpd = {version = "==0.2.1rc0"}
black = "*"
ipykernel = "*"
ipywidgets = "*"
isort = "*"
jupyter-cache = "*"
jupyterlab = ">=4"
jupyterlab-git = "*"
jupyterlab-lsp = "*"
jupyterlab_code_formatter = "*"
matplotlib = "*"
nbclient = "*"
nbformat = "*"
pandas = "*"
pre-commit = "*"
python-lsp-ruff = "*"
python-lsp-server = "*"
rope = "*"
ruff = "*"

[tasks.doc]
cmd = "quarto render"
cwd = "docs"
depends_on = ["install-julia"]
env = {PYTHONHASHSEED = "0"}

[tasks.doclive]
cmd = "quarto preview"
cwd = "docs"
depends_on = ["install-julia"]
env = {PYTHONHASHSEED = "0"}

[tasks.install-julia]
cmd = """
juliaup add 1.10.3 && \
juliaup default 1.10.3 && \
julia --project -e '
    using Pkg
    Pkg.add("IJulia")
    import IJulia
    IJulia.installkernel("julia-amplitude-serialization")
'
"""
