[project]
authors = [
    "Ilya Segal",
    "Mikhail Mikhasenko",
    "Remco de Boer",
]
channels = ["conda-forge"]
description = "Prototype for the amplitude model serialization format"
documentation = "https://rub-ep1.github.io/amplitude-serialization"
homepage = "https://rub-ep1.github.io/amplitude-serialization"
license = "MIT"
license-file = "LICENSE"
name = "amplitude-serialization"
platforms = [
    "linux-64",
    "osx-64",
    "osx-arm64",
]
repository = "https://github.com/RUB-EP1/amplitude-serialization"

[dependencies]
black = ">=24.4.2,<24.5"
ipykernel = "*"
isort = ">=5.13.2,<5.14"
juliaup = "*"
jupyter-cache = "*"
jupyterlab = ">=4.2.1,<4.3"
jupyterlab-git = ">=0.50.0,<0.51"
jupyterlab-lsp = ">=5.1.0,<5.2"
jupyterlab_code_formatter = ">=2.2.1,<2.3"
nbclient = "*"
nbformat = "*"
pre-commit = "*"
python = ">=3.8.0"
python-lsp-ruff = ">=2.2.0,<2.3"
python-lsp-server = ">=1.11.0,<1.12"
quarto = "*"
rope = ">=1.13.0,<1.14"
ruff = ">=0.4.5,<0.5"

[pypi-dependencies]
ampform-dpd = {version = "==0.2.1rc0"}

[tasks.doc]
cmd = "quarto render"
cwd = "docs"
depends_on = ["install-julia"]

[tasks.doclive]
cmd = "quarto preview"
cwd = "docs"
depends_on = ["install-julia"]

[tasks.install-julia]
cmd = """
juliaup add 1.10.3 && \
juliaup default 1.10.3 && \
julia --project -e '
    using Pkg
    Pkg.add("IJulia")
    import IJulia
    IJulia.installkernel("julia-amplitude-serialization")
'
"""
