name: Build HTML pages

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Julia cache
        uses: actions/cache@v4
        with:
          key: |
            julia-${{hashFiles('Manifest.toml')}}-${{hashFiles('**/*.jl')}}
          restore-keys: |
            julia-${{hashFiles('Manifest.toml')}}
            julia
          path: |
            ~/.julia/
      - uses: prefix-dev/setup-pixi@v0.6.0
        with:
          cache: true
      - name: Jupyter cache
        uses: actions/cache@v4
        with:
          key: |
            jupyter-cache-${{hashFiles('pixi.lock')}}-${{hashFiles('docs/*/*.md')}}
          restore-keys: |
            jupyter-cache-${{hashFiles('pixi.lock')}}
            jupyter-cache
          path: |
            **/.jupyter_cache
      - run: pixi run doc
      - if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    if: >-
      github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
